#  see documentation, e.g.
# - https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#declaring-project-metadata
# - https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
# - https://www.python.org/dev/peps/pep-0621/

[build-system]
requires = ["setuptools>=64.0.0", "setuptools-scm", "wheel"]
build-backend = "setuptools.build_meta"

[project]
authors = [
    { name = "Flavio Hafner", email = "f.hafner@esciencecenter.nl" },
    { name = "Malte Luken", email = "m.luken@esciencecenter.nl" },
    { name = "Angelica Maineri", email = "angelica@odissei-data.nl"},
    { name = "Qixiang Fang", email = "q.fang@uu.nl"},
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "duckdb",
    "polars",
    "numpy",
    "jupyter",
    "pyarrow",
    "sparqlwrapper",
    "pytest",
    "tqdm",
    "pandas>=2.0.3",
]
description = "Harvest Odissei Knowledge Graph for metadata of life events in CBS registry data"
keywords = ["cbs","metadata"]
license = {file = "LICENSE"}
name = "life_event_metadata"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.8"
version = "0.0.1"

[project.optional-dependencies]
dev = [
    "build",  # build is not only used in publishing (below), but also in the template's test suite
    "bump-my-version",
    "ruff>=0.15",
    "tox",
    "myst_parser",
    "prek",
]
publishing = [
    "build",
    "twine",
    "wheel",
]

[project.urls]
Repository = "https://github.com/odissei-data/teamnl-events-dataset/"
Issues = "https://github.com/odissei-data/teamnl-events-dataset/issues"
Changelog = "https://github.com/odissei-data/teamnl-events-dataset/CHANGELOG.md"





[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py38,py39,py310,py311,py312
skip_missing_interpreters = true

"""

[tool.ruff]
line-length = 120
output-format = "concise"

[tool.ruff.lint]
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Enable Pyflakes `E` and `F` codes by default.
select = ["ALL"]
ignore = [
    "ANN204", # Missing return type annotation for special (dunder) method
    "FBT",    # Using boolean function arguments
    "TD",     # TODOs
    "FIX001", # Resolve FIXMEs
    "FIX002", # Resolve TODOs
    "B028",   # No explicit `stacklevel` keyword argument found in warning
    # No docstrings required in the following cases
    "D100", # Missing module docstring
    "D104", # Missing public package docstring
    "D105", # Missing docstring in magic method
    "D107", # Missing docstring in `__init__`
    "COM812", # missing-trailing-comma; conflict with formatter
]
pydocstyle.convention = "numpy"

[tool.ruff.lint.per-file-ignores]
# Tests can ignore a few extra rules
"tests/**.py" = [
    "ANN201", # Missing return type annotation for public function
    "PT011",  # Missing `match` parameter in `pytest.raises()`
    "S101",   # Use of assert is detected
]
"notebooks/*ipynb" = [
    "T201", # print found
    "E501", # line too long
]


[tool.ruff.lint.isort]
known-first-party = ["life_event_metadata"]
force-single-line = true
no-lines-before = ["future","standard-library","third-party","first-party","local-folder"]

[tool.bumpversion]
current_version = "0.0.1"

[[tool.bumpversion.files]]
filename = "src/life_event_metadata/__init__.py"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
